<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .title {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .subtitle {
            font-size: 12px;
            color: #666;
            margin-bottom: 5px;
        }
        .info {
            font-size: 11px;
            color: #666;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f0f0f0;
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
            font-weight: bold;
            font-size: 11px;
        }
        td {
            border: 1px solid #ccc;
            padding: 8px;
            font-size: 11px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            font-size: 10px;
            color: #999;
            margin-top: 30px;
            text-align: center;
        }
        .note {
            font-size: 10px;
            color: #666;
            font-style: italic;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">SRS-MartPlace-09</div>
        <div class="title">Laporan Daftar Akun Penjual Berdasarkan Status</div>
        <div class="info">
            Tanggal dibuat: {{ \Carbon\Carbon::now()->format('d-m-Y') }} oleh {{ auth()->user()->name ?? 'System' }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">No</th>
                <th style="width: 20%;">Nama User</th>
                <th style="width: 20%;">Nama PIC</th>
                <th style="width: 30%;">Nama Toko</th>
                <th style="width: 15%;">Status</th>
                <th style="width: 10%;">Aktif</th>
            </tr>
        </thead>
        <tbody>
            @php
                // Sort: active first, then inactive
                $sortedSellers = collect($sellers)
                    ->sort(function ($a, $b) {
                        if ($a->is_active == $b->is_active) return 0;
                        return $a->is_active ? -1 : 1;
                    })
                    ->values();
            @endphp
            @forelse($sortedSellers as $index => $seller)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $seller->user->name ?? 'N/A' }}</td>
                    <td>{{ $seller->user->name ?? 'N/A' }}</td>
                    <td>{{ $seller->store_name }}</td>
                    <td>{{ ucfirst($seller->status) }}</td>
                    <td>{{ $seller->is_active ? 'Ya' : 'Tidak' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">Tidak ada data</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="note">
        ***) Data diurutkan berdasarkan status (Aktif dulu baru Tidak Aktif)
    </div>

    <div class="footer">
        Generated by SRS-MartPlace System
    </div>
</body>
</html>
